### ISSUE TITLE
not download

### ISSUE THREAD

**Issue by Kira5659** [massiveschlong/onlyfans-content-downloader#5]
after copying the java code to the console it starts to read or load the data and when it reaches 100% it only sends the message "Check the backend code terminal output for the download status" which is supposed to be done later. I would appreciate the help

**Comment by massiveschlong** [comment]
I don't know what your question is. Can you elaborate on what you need info of?

**Comment by Kira5659** [comment]
> no se cual es tu pregunta ¿Puedes dar más detalles sobre qué información necesitas?

Bro I have problems with the flasks and I installed them and it keeps throwing me the errors. Any solution?

**Comment by massiveschlong** [comment]
Sorry not trying to be annoying here but you aren't being specific as to what you are stuck on.

I guess you mean the dependencies. You share no screenshots or error messages and aren't providing any official naming terms (such as dependency).

I don't know what you need help with. Be specific. 

Also try to troubleshoot these problems thoroughly before contacting me because they are not related to my code. It's like calling your internet provider for printer issues. Totally not relevant. Out of service reach. 

Again, not trying to be a dick here. 🙏

Tip 1: make sure you install all dependencies in the read me file. Make sure your IDE (VSCode) is USING those dependencies. Find out on Google how you can check and set that. 

Tip 2: Google the error code and try to solve it.
